src/APIs/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from .views import UserInfoListView, SnippetDetail, ApoderadoInfo, DocenteInfo

urlpatterns = [

    url(r'^colegio_api/$', views.ColegioList.as_view()),
    url(r'^colegio_api/(?P<pk>\d+)/$', views.ColegioDetail.as_view()),
    url(r'^perfil_api/$', views.PerfilList.as_view()),
    url(r'^perfil_api/(?P<pk>\d+)/$', views.PerfilDetail.as_view()),
    ####################
    url(r'^apoderado_api/$', views.ApoderadoList.as_view()),
    url(r'^apoderado_api/(?P<pk>\d+)/$', views.ApoderadoDetail.as_view()),
    ###################
    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),
    ###################
    url(r'^apoderadoalumno_api/$', views.ApoderadoAlumnoList.as_view()),
    url(r'^apoderadoalumno_api/(?P<pk>\d+)/$', views.ApoderadoAlumnoDetail.as_view()),

    # http://127.0.0.1:8000/APIs/apoderadoalumno_api/?search=3

    ###################
    url(r'^matricula_api/$', views.MatriculaList.as_view()),
    url(r'^matricula_api/(?P<pk>\d+)/$', views.MatriculaDetail.as_view()),
    ###################

    # URL para el Web Service del Módulo Académico
    url(r'^asistencia_api/$', views.AsistenciaList.as_view()),
    url(r'^asistencia_api/(?P<pk>\d+)/$', views.AsistenciaDetail.as_view()),

    url(r'^aula_api/$', views.AulaList.as_view()),
    url(r'^aula_api/(?P<pk>\d+)/$', views.AulaDetail.as_view()),

    # url(r'^curso_docente_api/$', views.CursoDocenteList.as_view()),

    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),

    # URL para el Web Service del Módulo Académico
    url(r'^asistencia_api/$', views.AsistenciaList.as_view()),
    url(r'^asistencia_api/(?P<pk>\d+)/$', views.AsistenciaDetail.as_view()),

    url(r'^aula_api/$', views.AulaList.as_view()),
    url(r'^aula_api/(?P<pk>\d+)/$', views.AulaDetail.as_view()),

    # url(r'^curso_docente_api/$', views.CursoDocenteList.as_view()),


    url(r'^matricula_api/$', views.MatriculaList.as_view()),
    url(r'^matricula_api/(?P<pk>\d+)/$', views.MatriculaDetail.as_view()),

    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),

    url(r'^user_info/$', UserInfoListView.as_view(), name='user_info'),
    # url(r'^profesor_info/$', UserInfoListView.as_view(), name='profesor_info'),
    url(r'^apoderado_info/$', ApoderadoInfo, name='apoderado_info'),
    url(r'^docente_info/$', DocenteInfo, name='docente_info'),

    url(r'^colegio/(?P<pk>[0-9]+)/(?P<nombre>\w+)/$', SnippetDetail.as_view()),

    url(r'^curso_docente_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.CursoDocenteList.as_view()),

    # Web Service para obtener las ALUMNOS asociados a un aula determinado
    url(r'^aula_alumnos_api/(?P<pk>[0-9]+)/(?P<aula>\w+)/$', views.AulaAlumnosList.as_view()),

    # Web Service para obtener las CURSOS a las que enseña un docente determinado
    url(r'^docente_curso_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.DocenteCursoList.as_view()),

    # Web Service para obtener las AULAS a las que enseña un docente determinado
    url(r'^docente_aula_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.DocenteAulaList.as_view()),

    # Web Service para visualizar las ASISTENCIAS POR MES de un aula determinada
    url(r'^aula_asistencia_api/(?P<pk>[0-9]+)/(?P<aula>\w+)/(?P<mes>\w+)/$', views.AulaAsistenciaList.as_view()),

    # webservice prueba
    url(r'^relacionusuarioperfil/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.RelacionUsuarioPerfilView.as_view()),
    url(r'^relacionperfilalumno/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.RelacionPerfilAlumnoView.as_view()),

    #################################################################################################################
    url(r'^personaemisor_api/$', views.PersonaEmisorList.as_view()),
    url(r'^personaemisor_api/(?P<pk>\d+)/$', views.PersonaEmisorDetail.as_view()),
    ###################
    url(r'^personareceptor_api/$', views.PersonaReceptorList.as_view()),
    url(r'^personareceptor_api/(?P<pk>\d+)/$', views.PersonaReceptorDetail.as_view()),
    ###################
    url(r'^tipoalerta_api/$', views.TipoAlertaList.as_view()),
    url(r'^tipoalerta_api/(?P<pk>\d+)/$', views.TipoAlertaDetail.as_view()),
    ####################
    url(r'^estadoalerta_api/$', views.EstadoAlertaList.as_view()),
    url(r'^estadoalerta_api/(?P<pk>\d+)/$', views.EstadoAlertaDetail.as_view()),
    ###################
    url(r'^contenidoalerta_api/$', views.ContenidoAlertaList.as_view()),
    url(r'^contenidoalerta_api/(?P<pk>\d+)/$', views.ContenidoAlertaDetail.as_view()),
    ###################
    url(r'^alerta_api/$', views.AlertaList.as_view()),
    url(r'^alerta_api/(?P<pk>\d+)/$', views.AlertaDetail.as_view()),

    ###################
    url(r'^token_f/$', views.TokenFirebaseList.as_view()),
    url(r'^token_f/(?P<pk>\d+)/$', views.TokenFirebaseDetail.as_view()),
    ###################
    url(r'^usuarios_permisos/$', views.GroupList.as_view()),
    url(r'^usuarios_permisos/(?P<pk>\d+)/$', views.GroupDetail.as_view()),

    ###################
    url(r'^colegio_personal/$', views.PersonalColegioList.as_view()),
    url(r'^colegio_personal/(?P<pk>\d+)/$', views.PersonalColegioDetail.as_view()),

    ###################
    url(r'^personal/$', views.PersonalList.as_view()),
    url(r'^personal/(?P<pk>\d+)/$', views.PersonalDetail.as_view()),
    ###################
    url(r'^alertadata_api/$', views.AlertaDataList.as_view()),
    url(r'^alertadata_api/(?P<pk>\d+)/$', views.AlertaDataDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/cash/urls.py
from django.conf.urls import url
from .views import (
    index,
    # Import de vistas CRUD de Cashier
    CashierListView, CashierDetailView, CashierCreationView, CashierUpdateView, CashierDeleteView,
    # Import de vistas CRUD de BoxCashier
    BoxCashierListView, BoxCashierDetailView, BoxCashierCreationView, BoxCashierUpdateView, BoxCashierDeleteView,
    # Import de vistas CRUD de Consignment
    ConsignmentListView, ConsignmentDetailView, ConsignmentCreationView, ConsignmentUpdateView, ConsignmentDeleteView,
    # Import de vistas de Filtrado
    search,
)

urlpatterns = [
    # URL index 'localhost:8000/cash
    url(r'^$', index),

    # URL's del CRUD de CAJA
    url(r'^cashier/$', CashierListView.as_view(), name='cashier_list'),

    # url(r'^cashier/(?P<pk>\d+)$', CashierDetailView.as_view(), name='cashier_detail'),
    url(r'^cashier/(?P<pk>\d+)$', CashierDetailView.as_view(), name='cashier_detail'),

    url(r'^cashier/create$', CashierCreationView.as_view(), name='cashier_create'),
    url(r'^cashier/update/(?P<pk>\d+)$', CashierUpdateView.as_view(), name='cashier_edit'),
    url(r'^cashier/delete/(?P<pk>\d+)$', CashierDeleteView.as_view(), name='cashier_delete'),

    # URL's del CRUD de CAJACAJERO
    url(r'^boxcashier/$', BoxCashierListView.as_view(), name='boxcashier_list'),
    url(r'^boxcashier/(?P<pk>\d+)$', BoxCashierDetailView.as_view(), name='boxcashier_detail'),

    url(r'^boxcashier/Aperturar$', BoxCashierCreationView.as_view(), name='boxcashier_AperturarCaja'),
    url(r'^boxcashier/Cerrar/(?P<pk>\d+)$', BoxCashierUpdateView.as_view(), name='boxcashier_CerrarCaja'),

    url(r'^boxcashier/delete/(?P<pk>\d+)$', BoxCashierDeleteView.as_view(), name='boxcashier_delete'),

    # URL's del CRUD de Remesas

    # url(r'^search/$', search, name='search'),
    # url(r'^consignment/$', ConsignmentListView.as_view(), name='consignment_list'),
    url(r'^consignment/$', search, name='consignment_list'),
    url(r'^consignment/(?P<pk>\d+)$', ConsignmentDetailView.as_view(), name='consignment_detail'),
    url(r'^consignment/create$', ConsignmentCreationView.as_view(), name='consignment_create'),
    url(r'^consignment/update/(?P<pk>\d+)$', ConsignmentUpdateView.as_view(), name='consignment_edit'),
    url(r'^consignment/delete/(?P<pk>\d+)$', ConsignmentDeleteView.as_view(), name='consignment_delete'),

]

src/colegio/urls.py
from django.conf.urls import include, url
from django.conf.urls import handler404
from colegio.views import mi_error_404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import enrollment.urls
import register.urls
import income.urls
import cash.urls
import payments.urls
import discounts.urls
import AE_academico.urls
import APIs.urls
import alerta.urls
from . import views

handler404 = mi_error_404

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^enrollments/', include(enrollment.urls, namespace='enrollments')),
    url(r'^registers/', include(register.urls, namespace='registers')),
    url(r'^cash/', include(cash.urls, namespace='cash')),
    url(r'^income/', include(income.urls, namespace='income')),
    url(r'^payments/', include(payments.urls, namespace='payments')),
    url(r'^discounts/', include(discounts.urls, namespace='discounts')),
    url(r'^academic/', include(AE_academico.urls, namespace='academic')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^APIs/', include(APIs.urls, namespace='apis')),
    url(r'^alerta/', include(alerta.urls, namespace='alerta')),

    url(r'^locale/', views.view_locale),
    url(r'^login_api/', views.Login_api_general.as_view()),
# url(r'^calendar/', include('schedule.urls', namespace='calendar')),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
                       url(r'^__debug__/', include(debug_toolbar.urls)),
                   ] + urlpatterns

src/cash/forms.py
from django import forms
from .models import Caja, CajaCajero, Remesa
from django.db.models import Count




class CashierForm(forms.ModelForm):
    class Meta:
        model = Caja

        fields = [
            'colegio',
            'numero',
            'descripcion',
            'activo',
            'eliminado',
            'fecha_creacion',
            'fecha_modificacion',
            'usuario_creacion',
            'usuario_modificacion',
        ]

        labels = {
            'colegio': 'Colegio',
            'numero': 'Número de Caja',
            'descripcion': 'Descripción',
            'activo': 'Activo',
            'eliminado': 'Eliminado',
            'fecha_creacion': 'Fecha de Creación',
            'fecha_modificacion': 'Fecha de Modificación',
            'usuario_creacion': 'Usuario creación',
            'usuario_modificacion': 'Usuario Modificación',
        }

        widgets = {

            'colegio': forms.Select(attrs={'class': 'hidden'}),
            'numero': forms.TextInput(attrs={'class': 'form-control', 'onKeyPress': 'return soloNumeros(event)', 'tabindex': '1', 'maxlength': 4}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': '3', 'tabindex': '2'}),
            'activo': forms.CheckboxInput(),
            'eliminado': forms.CheckboxInput(),
            'fecha_creacion': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_modificacion': forms.TextInput(attrs={'class': 'form-control'}),
            'usuario_creacion': forms.HiddenInput(attrs={'class': 'form-control'}),
            'usuario_modificacion': forms.HiddenInput(attrs={'class': 'form-control'}),
        }


class BoxCashierForm(forms.ModelForm):
    class Meta:
        model = CajaCajero

        fields = [
            'personal_colegio',
            'caja',
            'saldo',
            'monto_apertura',
            'monto_cierre',
            'comentario_apertura',
            'comentario_cierre',
            'estado',
            'fecha_creacion',
            'fecha_modificacion',
            'usuario_creacion',
            'usuario_modificacion',
        ]

        labels = {
            'personal_colegio': 'Cajero',
            'caja': 'N° de Caja',
            'saldo': 'Saldo',
            'monto_apertura': 'Monto de Apertura',
            'monto_cierre': 'Monto de Cierre',
            'comentario_apertura': 'Comentario Apertura',
            'comentario_cierre': 'Comentario Cierre',
            'estado': 'Estado',
            'fecha_creacion': 'Fecha de Creación',
            'fecha_modificacion': 'Fecha de Modificación',
            'usuario_creacion': 'Usuario de Creación',
            'usuario_modificacion': 'Usuario de Modificación',
        }

        widgets = {

            'personal_colegio': forms.Select(attrs={'class': 'form-control'}),
            #'caja': forms.ModelChoiceField(queryset= Caja.objects.filter(colegio_id=1), to_field_name="id_caja"),

            'caja': forms.Select(attrs={'class': 'form-control'}),
            'saldo': forms.TextInput(attrs={'class': 'form-control'}),
            'monto_apertura': forms.TextInput(attrs={'class': 'form-control'}),
            'monto_cierre': forms.TextInput(attrs={'class': 'form-control', 'onfocus': 'deleteText(this)'}),
            'comentario_apertura': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'comentario_cierre': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'estado': forms.CheckboxInput(attrs={'id': 'Uncheck'}),
            'fecha_creacion': forms.HiddenInput(attrs={'class': 'form-control'}),
            'fecha_modificacion': forms.HiddenInput(attrs={'class': 'form-control'}),
            'usuario_creacion': forms.HiddenInput(attrs={'class': 'form-control'}),
            'usuario_modificacion': forms.HiddenInput(attrs={'class': 'form-control'}),
        }


class ConsignmentForm(forms.ModelForm):
    class Meta:
        model = Remesa

        fields = [
            'personal_colegio',
            'movimiento',
            'fechacreacion',
            'monto',
            'comentario',
            'pusu'
        ]

        labels = {
            'personal_colegio': 'Persona Encargada',
            'movimiento': 'Cajero',
            'fechacreacion': 'Fecha Creación',
            'monto': 'Monto',
            'comentario': 'Comentario',
            'pusu': 'Usuario_contraseña'
        }

        widgets = {

            'personal_colegio': forms.Select(attrs={'class': 'form-control', 'id': 'personaTxt', 'name': 'personaTxt',
                                                    'onchange': 'personaSelect()', 'tabindex': '1'}),
            'movimiento': forms.Select(attrs={'class': 'form-control'}),
            'fechacreacion': forms.HiddenInput(attrs={'class': 'form-control'}),
            'monto': forms.TextInput(
                attrs={'class': 'form-control', 'name': 'inputMonto', 'onKeyPress': 'return NumCheck(event, this)',
                       'placeholder': 'Escribe el monto a entregar',
                       "onchange": "document.getElementById('monto').innerHTML = montodine = this.value", 'tabindex': '2'}),
            'comentario': forms.Textarea(attrs={'class': 'form-control', 'rows': '3', 'tabindex': '3'}),
            'pusu': forms.TextInput(attrs={'id': 'n222', 'name': 'n222'}),
        }

class CajaChicaConsignmentForm(forms.ModelForm):
    class Meta:
        model = Remesa

        fields = [
            'personal_colegio',
            'movimiento',
            'fechacreacion',
            'monto',
            'comentario',
        ]

        labels = {
            'personal_colegio': 'Persona Encargada',

            'movimiento': 'Cajero',
            'fechacreacion': 'Fecha Creación',
            'monto': 'Monto',
            'comentario': 'Comentario',
        }

        widgets = {

            'personal_colegio': forms.Select(attrs={'class': 'form-control', 'id': 'personaTxt', 'name': 'personaTxt',
                                                    'onchange': 'personaSelect()', 'tabindex': '1'}),
            'movimiento': forms.Select(attrs={'class': 'form-control'}),
            'fechacreacion': forms.HiddenInput(attrs={'class': 'form-control'}),
            'monto': forms.TextInput(
                attrs={'class': 'form-control', 'name': 'inputMonto', 'onKeyPress': 'return NumCheck(event, this)',
                       'placeholder': 'Escribe el monto a entregar',
                       "onchange": "document.getElementById('monto').innerHTML = montodine = this.value", 'tabindex': '2'}),
            'comentario': forms.Textarea(attrs={'class': 'form-control', 'rows': '3', 'tabindex': '3'}),
        }

src/cash/templates/cashier/cashier_form.html
{% extends "page.html" %}
{% block titulo %}
    <h1>Cajas
        {{ block.super }}
        <small>Módulo de Facturación</small>
    </h1>
{% endblock %}
{% block container %}
<div class="box box-primary">
    <div class="box-header with-border">
            <div class="box-body">
                <div class="col-md-9">
                    <div class="panel-page">
                        <div class="box-body">
                            <form class="form-horizontal" action="" method="post">
                                {% csrf_token %}
                                <div style="display: none;">
                                {{ form.colegio }}
                                {{ form.activo }}
                                {{ form.fecha_creacion }}
                                {{ form.fecha_modificacion }}
                                {{ form.usuario_creacion }}
                                {{ form.usuario_modificacion }}
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Numero de Caja</label>
                                    <div class="col-sm-10">
                                        {{ form.numero }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Descripcion</label>
                                    <div class="col-sm-10">
                                        {{ form.descripcion }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <a href="{% url 'cash:cashier_list'  %}" class="btn btn-default" >
                                            <i class="fa fa-arrow-left" aria-hidden="true"></i> Volver a lista
                                        </a>
                                        <button type="submit" class="btn btn-success" tabindex="3">
                                            <i class="fa fa-plus" aria-hidden="true"></i> Registrar Caja
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">

                </div>
            </div>
        </div>
    </div>

{% endblock container %}
{% block scripts %}
<script type="text/javascript">
  //Solo permite ingresar numeros

        function soloNumeros(e){
            var key = window.Event ? e.which : e.keyCode
            return (key >= 48 && key <= 57)}

</script>
{% endblock scripts %}

src/cash/templates/cashier/cashier_list.html
{% extends "page.html" %}

{% block title %}{{ block.super }}Facturación{% endblock %}

{% block titulo %}
    <h1>
        Lista de Cajas
        <small>Módúlo de Facturación</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li>Módúlo de Facturación</li>
        <li class="active">Lista de Cajas</li>
    </ol>
{% endblock %}

{% block container %}
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <!--Comienza el contenido!!!!!!!!!!!!!!!!!!!-->
    <section>
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                       
                        <div class="box-body">
                            <div class="col-md-9">
                                <div class="panel-page">
                                    {% if es_tesorero %}
                                        <div class="toolbar-header">
                                            <a class="btn btn-success" href='{% url "cash:cashier_create" %}'><i
                                                    class="fa fa-plus" aria-hidden="true"></i> Crear caja</a>
                                        </div>
                                    {% endif %}


                                    <div class="box-header with-border">
                                        <h3 class="box-title">Lista de Cajas</h3>
                                    </div>
                                    <div class="box-body">
                                        <div class="table-responsive no-padding">

                                            <table class="table table-hover">
                                                <tbody>
                                                <tr>
                                                    <th>Ítem</th>
                                                    <th>Número de Caja</th>
                                                    <th>Descripción</th>
                                                    <!-- <th>Estado</th>
                                                    <th>Eliminado</th> -->
                                                    <th>Acciones</th>

                                                </tr>
                                                {% for cashier in object_list %}
                                                    {% if cashier.colegio.id_colegio == idcolegio %}
                                                        <tr>
                                                            {% if cashier.eliminado == False %}
                                                            {% else %}
                                                                <td>{{ forloop.counter }}</td>
                                                                <td>{{ cashier.numero }}</td>
                                                                {% if cashier.descripcion == None %}
                                                                    <td>No hay descripción</td>
                                                                {% else %}
                                                                    <td>{{ cashier.descripcion }}</td>
                                                                {% endif %}


                                                                <!--

                                                    <td>
                                                        {% if cashier.activo == 1 %}
                                                            <span class="label label-success">Activo</span>
                                                        {% else %}
                                                            <span class="label label-danger">Desactivado</span>
                                                        {% endif %}
                                                    </td>
                                                    <td>{{ cashier.eliminado }}</td> -->

                                                                <td>
                                                                    <div class="btn-group btn-group-sm" role="group"
                                                                         aria-label="...">
                                                                        {% if permiso_para_editar == True %}
                                                                            <a title="Editar"
                                                                               href='{% url "cash:cashier_edit" cashier.id_caja %}'
                                                                               class="btn btn-default">
                                                                                <i class="fa fa-pencil"
                                                                                   aria-hidden="true"></i>
                                                                            </a>
                                                                        {% else %}

                                                                            <a title="Editar"
                                                                               onclick="no_tiene_permisos()"
                                                                               class="btn btn-default">
                                                                                <i class="fa fa-pencil"
                                                                                   aria-hidden="true"></i>
                                                                            </a>
                                                                            <script>
                                                                                function no_tiene_permisos() {
                                                                                    alert("Este usuario no tiene privilegios para modificar caja. Contacte con el tesorero");
                                                                                }
                                                                            </script>
                                                                        {% endif %}

                                                                        <a title="Detalle"
                                                                           href='{% url "cash:cashier_detail" cashier.id_caja %}'
                                                                           class="btn btn-default">
                                                                            <i class="fa fa-info-circle"
                                                                               aria-hidden="true"></i>
                                                                        </a>
                                                                        <!--<a title="Eliminar" href="{% url 'cash:cashier_delete' cashier.id_caja %}" class="btn btn-default">
                                                                <i class="fa fa-trash" aria-hidden="true"></i>
                                                            </a>-->
                                                                    </div>
                                                                </td>
                                                            {% endif %}

                                                        </tr>
                                                    {% endif %}
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- /.FIN DE CONTENIDO -->
    <!-- /.FIN DE CONTENEDOR DE FORMULARIO  -->



    <!--Fin del contenido!!!!!!!!!!!-->

{% endblock container %}