src/APIs/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from .views import UserInfoListView, SnippetDetail, ApoderadoInfo, DocenteInfo

urlpatterns = [

    url(r'^colegio_api/$', views.ColegioList.as_view()),
    url(r'^colegio_api/(?P<pk>\d+)/$', views.ColegioDetail.as_view()),
    url(r'^perfil_api/$', views.PerfilList.as_view()),
    url(r'^perfil_api/(?P<pk>\d+)/$', views.PerfilDetail.as_view()),
    ####################
    url(r'^apoderado_api/$', views.ApoderadoList.as_view()),
    url(r'^apoderado_api/(?P<pk>\d+)/$', views.ApoderadoDetail.as_view()),
    ###################
    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),
    ###################
    url(r'^apoderadoalumno_api/$', views.ApoderadoAlumnoList.as_view()),
    url(r'^apoderadoalumno_api/(?P<pk>\d+)/$', views.ApoderadoAlumnoDetail.as_view()),

    # http://127.0.0.1:8000/APIs/apoderadoalumno_api/?search=3

    ###################
    url(r'^matricula_api/$', views.MatriculaList.as_view()),
    url(r'^matricula_api/(?P<pk>\d+)/$', views.MatriculaDetail.as_view()),
    ###################

    # URL para el Web Service del Módulo Académico
    url(r'^asistencia_api/$', views.AsistenciaList.as_view()),
    url(r'^asistencia_api/(?P<pk>\d+)/$', views.AsistenciaDetail.as_view()),

    url(r'^aula_api/$', views.AulaList.as_view()),
    url(r'^aula_api/(?P<pk>\d+)/$', views.AulaDetail.as_view()),

    # url(r'^curso_docente_api/$', views.CursoDocenteList.as_view()),

    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),

    # URL para el Web Service del Módulo Académico
    url(r'^asistencia_api/$', views.AsistenciaList.as_view()),
    url(r'^asistencia_api/(?P<pk>\d+)/$', views.AsistenciaDetail.as_view()),

    url(r'^aula_api/$', views.AulaList.as_view()),
    url(r'^aula_api/(?P<pk>\d+)/$', views.AulaDetail.as_view()),

    # url(r'^curso_docente_api/$', views.CursoDocenteList.as_view()),


    url(r'^matricula_api/$', views.MatriculaList.as_view()),
    url(r'^matricula_api/(?P<pk>\d+)/$', views.MatriculaDetail.as_view()),

    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),

    url(r'^user_info/$', UserInfoListView.as_view(), name='user_info'),
    # url(r'^profesor_info/$', UserInfoListView.as_view(), name='profesor_info'),
    url(r'^apoderado_info/$', ApoderadoInfo, name='apoderado_info'),
    url(r'^docente_info/$', DocenteInfo, name='docente_info'),

    url(r'^colegio/(?P<pk>[0-9]+)/(?P<nombre>\w+)/$', SnippetDetail.as_view()),

    url(r'^curso_docente_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.CursoDocenteList.as_view()),

    # Web Service para obtener las ALUMNOS asociados a un aula determinado
    url(r'^aula_alumnos_api/(?P<pk>[0-9]+)/(?P<aula>\w+)/$', views.AulaAlumnosList.as_view()),

    # Web Service para obtener las CURSOS a las que enseña un docente determinado
    url(r'^docente_curso_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.DocenteCursoList.as_view()),

    # Web Service para obtener las AULAS a las que enseña un docente determinado
    url(r'^docente_aula_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.DocenteAulaList.as_view()),

    # Web Service para visualizar las ASISTENCIAS POR MES de un aula determinada
    url(r'^aula_asistencia_api/(?P<pk>[0-9]+)/(?P<aula>\w+)/(?P<mes>\w+)/$', views.AulaAsistenciaList.as_view()),

    # webservice prueba
    url(r'^relacionusuarioperfil/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.RelacionUsuarioPerfilView.as_view()),
    url(r'^relacionperfilalumno/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.RelacionPerfilAlumnoView.as_view()),

    #################################################################################################################
    url(r'^personaemisor_api/$', views.PersonaEmisorList.as_view()),
    url(r'^personaemisor_api/(?P<pk>\d+)/$', views.PersonaEmisorDetail.as_view()),
    ###################
    url(r'^personareceptor_api/$', views.PersonaReceptorList.as_view()),
    url(r'^personareceptor_api/(?P<pk>\d+)/$', views.PersonaReceptorDetail.as_view()),
    ###################
    url(r'^tipoalerta_api/$', views.TipoAlertaList.as_view()),
    url(r'^tipoalerta_api/(?P<pk>\d+)/$', views.TipoAlertaDetail.as_view()),
    ####################
    url(r'^estadoalerta_api/$', views.EstadoAlertaList.as_view()),
    url(r'^estadoalerta_api/(?P<pk>\d+)/$', views.EstadoAlertaDetail.as_view()),
    ###################
    url(r'^contenidoalerta_api/$', views.ContenidoAlertaList.as_view()),
    url(r'^contenidoalerta_api/(?P<pk>\d+)/$', views.ContenidoAlertaDetail.as_view()),
    ###################
    url(r'^alerta_api/$', views.AlertaList.as_view()),
    url(r'^alerta_api/(?P<pk>\d+)/$', views.AlertaDetail.as_view()),

    ###################
    url(r'^token_f/$', views.TokenFirebaseList.as_view()),
    url(r'^token_f/(?P<pk>\d+)/$', views.TokenFirebaseDetail.as_view()),
    ###################
    url(r'^usuarios_permisos/$', views.GroupList.as_view()),
    url(r'^usuarios_permisos/(?P<pk>\d+)/$', views.GroupDetail.as_view()),

    ###################
    url(r'^colegio_personal/$', views.PersonalColegioList.as_view()),
    url(r'^colegio_personal/(?P<pk>\d+)/$', views.PersonalColegioDetail.as_view()),

    ###################
    url(r'^personal/$', views.PersonalList.as_view()),
    url(r'^personal/(?P<pk>\d+)/$', views.PersonalDetail.as_view()),
    ###################
    url(r'^alertadata_api/$', views.AlertaDataList.as_view()),
    url(r'^alertadata_api/(?P<pk>\d+)/$', views.AlertaDataDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/colegio/urls.py
from django.conf.urls import include, url
from django.conf.urls import handler404
from colegio.views import mi_error_404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import enrollment.urls
import register.urls
import income.urls
import cash.urls
import payments.urls
import discounts.urls
import AE_academico.urls
import APIs.urls
import alerta.urls
from . import views

handler404 = mi_error_404

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^enrollments/', include(enrollment.urls, namespace='enrollments')),
    url(r'^registers/', include(register.urls, namespace='registers')),
    url(r'^cash/', include(cash.urls, namespace='cash')),
    url(r'^income/', include(income.urls, namespace='income')),
    url(r'^payments/', include(payments.urls, namespace='payments')),
    url(r'^discounts/', include(discounts.urls, namespace='discounts')),
    url(r'^academic/', include(AE_academico.urls, namespace='academic')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^APIs/', include(APIs.urls, namespace='apis')),
    url(r'^alerta/', include(alerta.urls, namespace='alerta')),

    url(r'^locale/', views.view_locale),
    url(r'^login_api/', views.Login_api_general.as_view()),
# url(r'^calendar/', include('schedule.urls', namespace='calendar')),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
                       url(r'^__debug__/', include(debug_toolbar.urls)),
                   ] + urlpatterns

src/payments/urls.py
from django.conf.urls import url
from .views import (
    # Import de vistas CRUD de TipoPago
    TipoPagoListView, TipoPagoDetailView, TipoPagoCreationView, TipoPagoUpdateView, TipoPagoDeleteView,

)
from payments.views import ControlPagosPromotorView, exportPagoCSV
from payments.views import RegistrarPagoCreateView, ControlPagosDirectorView


urlpatterns = [
    # URL's del CRUD de TipoPago
    url(r'^tipo_pago/$', TipoPagoListView.as_view(), name='tipopago_list'),
    url(r'^tipo_pago/(?P<pk>\d+)$', TipoPagoDetailView.as_view(), name='tipopago_detail'),
    url(r'^tipo_pago/create$', TipoPagoCreationView.as_view(), name='tipopago_create'),
    url(r'^tipo_pago/update/(?P<pk>\d+)$', TipoPagoUpdateView.as_view(), name='tipopago_edit'),
    url(r'^tipo_pago/delete/(?P<pk>\d+)$', TipoPagoDeleteView.as_view(), name='tipopago_delete'),
    url(r'^register/create/$', RegistrarPagoCreateView.as_view(), name='registrarpago_create'),
    url(r'^pago_promotor/filter', ControlPagosPromotorView.as_view(), name="pago_promotor"),
    url(r'^lista/$', ControlPagosDirectorView.as_view(), name="lista"),

    url(r'^exportPagoCSV/', exportPagoCSV, name='exportPago'),
]

src/payments/models.py
from django.db import models

# Create your models here.
from register.models import Proveedor, Sucursal, PersonalSucursal, ProveedorSucursal
from utils.models import ActivoMixin, CreacionModificacionFechaMixin, CreacionModificacionUserMixin
from utils.middleware import get_current_colegio
from income.models import obtener_mes

class Eliminar(models.Model):
    """
    Clase para cambiar de estado automaticamente segun guardado o update
    """
    eliminado = models.BooleanField()

    def save(self, *args, **kwargs):
        # creación
        if not self.pk:
            self.eliminado = False

        else:  # modificacion
            self.eliminado = True

        super(Eliminar, self).save(*args, **kwargs)

    save.alters_data = True

    class Meta:
        abstract = True


class TipoPago(ActivoMixin, Eliminar, models.Model):
    """
    Clase para definir y organizar los tipos de pagos que realiza el colegio
    """
    id_tipo_pago = models.AutoField(primary_key=True)
    colegio = models.ForeignKey(Sucursal, models.DO_NOTHING, db_column='id_colegio', default=get_current_colegio)
    descripcion = models.CharField(max_length=100)
    tipo = models.IntegerField(blank=True, null=True)
    padre = models.ForeignKey("self", models.DO_NOTHING, db_column="id_parent", blank=True, null=True)

    def __str__(self):
        """
        Devuelve la descripción del TIPOPAGO. Ejemplo :
        :return Pago de agua
        """

        return "{0}".format(self.descripcion)

    class Meta:
        managed = True
        ordering = ["id_tipo_pago"]
        #db_table = 'tipo_pago'
        permissions = (
            ("Tipo_Pago_List", "ver lista de tipo de pago"),
            ("Tipo_Pago_Detail", "ver detalle de tipo de pago"),
            ("Tipo_Pago_Update", "modificar tipo de pago"),
            ("Tipo_Pago_Creation", "crear tipo de pago"),
            ("Tipo_Pago_Delete", "eliminar tipo de pago"),
        )


class CajaChica(CreacionModificacionFechaMixin, CreacionModificacionUserMixin):
    """
    Clase para definir el monto que dispondrá un colegio para destinar a los pagos varios
    """
    id_caja_chica = models.AutoField(primary_key=True)
    colegio = models.ForeignKey(Sucursal, models.DO_NOTHING, db_column="id_colegio", related_name="caja_chica")
    presupuesto = models.FloatField()
    periodo = models.IntegerField()
    saldo = models.FloatField()

    class Meta:
        managed = True
        #db_table = 'caja_chica'


class Pago(CreacionModificacionFechaMixin, CreacionModificacionUserMixin):
    """
    Clase para definir los pagos que el colegio realiza por los diferentes conceptos
    """
    id_pago = models.AutoField(primary_key=True)
    proveedor = models.ForeignKey(ProveedorSucursal, models.DO_NOTHING, db_column="id_proveedor_colegio")
    caja_chica = models.ForeignKey(CajaChica, models.DO_NOTHING, db_column="id_caja_chica", related_name="pagos")
    personal = models.ForeignKey(PersonalSucursal, models.DO_NOTHING, db_column="id_personal_colegio", related_name="pagos")
    tipo_pago = models.ForeignKey(TipoPago, models.DO_NOTHING, db_column="id_tipo_pago", related_name="pagos")
    descripcion = models.CharField(max_length=200)
    monto = models.FloatField()
    fecha = models.DateTimeField()
    numero_comprobante = models.CharField(max_length=30)

    class Meta:
        managed = True
        #db_table = 'pago'
        permissions = (
            ('control_pagos', 'Para el control de pagos realizados'),
            ("Registrar_Pago_Create","crear registro de pago"),
            
        )


def calculo_pagos_total(id_colegio, anio, tipo_pago, mes):

    # Proceso de filtrado según colegio
    pago_0 = Pago.objects.filter(caja_chica__colegio__id_colegio=id_colegio)

    # Proceso de filtrado según el año
    anio = int(anio)
    pago_1 = pago_0.filter(fecha__year=anio)

    # Proceso de filtrado según el tipo de pago
    if tipo_pago == "Todos":
        pago_2 = pago_1
    else:
        pago_2 = pago_1.filter(tipo_pago=tipo_pago)

    # Proceso de filtrado según el numero comprobante de pago
    if mes == "Todos":
        pago_3 = pago_2
    else:
        num_mes = obtener_mes(mes)
        pago_3 = pago_2.filter(fecha__month=num_mes)

    return pago_3

src/payments/forms.py
from django import forms
from django.forms import ModelForm
from payments.models import TipoPago
from payments.models import Pago
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper
from utils.middleware import get_current_colegio

class TipoPagoForm(forms.ModelForm):
    class Meta:
        model = TipoPago

        fields = [

            'colegio',
            'descripcion',
            'tipo',
            'padre',
            'eliminado',
        ]

        labels = {

            'colegio': 'Colegio',
            'descripcion': 'Descripción',
            'tipo': 'Tipo',
            'padre': 'Padre',
            'eliminado': 'Eliminado',
        }

        widgets = {

            'colegio': forms.Select(attrs={'class': 'hidden'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'tipo': forms.TextInput(attrs={'class': 'hidden', 'id': 'describe', 'name': 'lname'}),
            'padre': forms.Select(attrs={'class': 'form-control'}),
            'eliminado': forms.CheckboxInput(),
        }


class PagoForm(ModelForm):

    class Meta:
        model = Pago

        fields = [
            'proveedor',
            'tipo_pago',
            'descripcion',
            'monto',
            'numero_comprobante',
        ]

        labels = {

            'proveedor':_('Proveedor'),
            'tipo_pago':_('Tipo de Pago'),
            'descripcion':_('Descripción'),
            'monto':_('Monto(S/.)'),
            'numero_comprobante':_('N° Comprobante'),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['proveedor'].widget.attrs.update({'class': 'form-control'})
        self.fields['tipo_pago'].widget.attrs.update({'class': 'form-control'})
        self.fields['descripcion'].widget.attrs.update({'class': 'form-control'})
        self.fields['monto'].widget.attrs.update({'class': 'form-control'})
        self.fields['numero_comprobante'].widget.attrs.update({'class': 'form-control'})


class ControlPagosPromotorForm(forms.Form):
    """
    Formulario para filtar los detalles de Control de pagos
    Nota:
        solo se añaden com campos los que son definidos por los usuarios
    """
    tipo_pago = forms.ModelChoiceField(
        label='Tipo_pago',
        queryset=None,
        required=False, )

    anio = forms.CharField()
    mes = forms.CharField()
    fecha_inicio = forms.DateField()
    fecha_final = forms.DateField()

    def ChoiceAnio(self):
        MY_CHOICES = (
            ('2017', '2017'),
            ('2016', '2016'),
        )
        return MY_CHOICES

    def ChoiceMes(self):
        MY_CHOICES = (
            ('Todos', 'Todos'),
            ('Enero', 'Enero'),
            ('Febrero', 'Febrero'),
            ('Marzo', 'Marzo'),
            ('Abril', 'Abril'),
            ('Mayo', 'Mayo'),
            ('Junio', 'Junio'),
            ('Julio', 'Julio'),
            ('Agosto', 'Agosto'),
            ('Setiembre', 'Setiembre'),
            ('Octubre', 'Octubre'),
            ('Noviembre', 'Noviembre'),
            ('Diciembre', 'Diciembre'),
        )
        return MY_CHOICES

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['anio'] = forms.ChoiceField(choices=self.ChoiceAnio())
        self.fields['anio'].widget.attrs.update({'class': 'form-control'})
        self.fields['mes'] = forms.ChoiceField(choices=self.ChoiceMes())
        self.fields['mes'].widget.attrs.update({'class': 'form-control'})
        self.fields['tipo_pago'].widget.attrs.update({'class': 'form-control'})

        colegio = get_current_colegio()
        tipos = TipoPago.objects.filter(colegio=colegio)

        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.fields['tipo_pago'].queryset = tipos

src/payments/templates/TipoPago/tipopago_list.html
{% extends "page.html" %}

{% block title %}{{ block.super }}Pagos{% endblock %}

<!-- HEADER INFO PAGE UBICACION -->
{% block titulo %}
      <h1>
        Tipos de Pagos
        <small>Módulo de Facturación</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li>Módulo de Facturación</li>
        <li class="active">Lista de Tipos de Pagos</li>
      </ol>
{% endblock %}
<!-- FIN DE INFO PAGE UBICACION -->

{% block container %}

  <!-- INICIA CONTENDOR DE FORMULARIOS -->
  <div>
    <!-- INICIO DE CONTENIDO -->
    <section>
      <div class="row">
          <div class="col-md-12">
              <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Lista de Tipos de Pagos</h3>
                </div>
                <div class="box-body">
                  <div class="col-md-9">
                    <div class="panel-page">

                      <div class="panel-body">

                        <div class="toolbar-header">
                            <a class="btn btn-success" href="{% url 'payments:tipopago_create' %}"><i class="fa fa-plus" aria-hidden="true"></i>Registrar Tipo de Pago</a>
                        </div>
                        <!-- INICIA LA LISTA DE REGISTROS -->
                        <div class="page-header">

                          <h3>Bienes</h3>
                        </div>
                          <!-- Bienes -->

                          <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                              <div class="panel panel-default">
                                  <div class="panel-heading">
                                      <h4 class="panel-title">
                                          <a data-toggle="collapse" data-parent="#accordion1" href="#collapseOne" class="" aria-expanded="true">
                                              Bienes</a>
                                      </h4>
                                  </div>
                                  <div id="collapseOne" class="panel-collapse collapse" aria-expanded="true">
                                      <div class="panel-body">
                                          <div class="panel-group" id="accordion2">
                                                <div class="panel-body">
                                                    <!-- <p>Es un bien, no esta eliminado y No tiene ID_PARENT, Como no tienen padre muestran descripción</p>
                                                    Panel 1                                -->
                                                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                                        <div class="panel-body">
                                                            <h4>Lista de Bienes</h4>
                                                            <table class="table">
                                                                <tr class="table-header">
                                                                    <th>Ítem</th>
                                                                    <th>Descripción</th>
                                                                    <th>Acciones</th>
                                                                </tr>
                                                                <tbody>
                                                                {% for tipopago in list_tipo_pago %}
                                                                    {% if tipopago.tipo == 0 and tipopago.eliminado == 0  %}
                                                                        {% if tipopago.padre == None %}
                                                                            <tr>
                                                                                <th scope="row">{{ forloop.counter }}</th>
                                                                                <td>{{ tipopago.descripcion }}</td>
                                                                                <td>
                                                                                    <div class="btn-group btn-group-sm" role="group" aria-label="...">

                                                                                        <a title="Detalle" href='{% url "payments:tipopago_detail" tipopago.id_tipo_pago %}' class="btn btn-default">
                                                                                            <i class="fa fa-info-circle" aria-hidden="true"></i>
                                                                                        </a>
                                                                                        <a title="Eliminar" href="{% url 'payments:tipopago_delete' tipopago.id_tipo_pago %}" class="btn btn-default">
                                                                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                                                                        </a>
                                                                                    </div>
                                                                                </td>
                                                                            </tr>
                                                                        {% endif %}
                                                                    {% endif %}
                                                                {% endfor %}
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>

                          </div>

                        <!-- FIN DE Bienes -->

                        <div class="page-header">
                          <h3>Servicios</h3>
                        </div>

                        <!-- Servicios -->

                          <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                              <div class="panel panel-default">
                                  <div class="panel-heading">
                                      <h4 class="panel-title">
                                          <a data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo" class="" aria-expanded="true">
                                              Servicios</a>
                                      </h4>
                                  </div>
                                  <div id="collapseTwo" class="panel-collapse collapse" aria-expanded="true">
                                      <div class="panel-body">
                                          <div class="panel-group" id="accordion2">

                                              <div class="panel-body">
                                                    <!-- <p>Es un bien, no esta eliminado y No tiene ID_PARENT, Como no tienen padre muestran descripción</p>
                                                    Panel 1                                -->
                                                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                                        <div class="panel-body">
                                                            <h4>Lista de Servicios</h4>
                                                            <table class="table">
                                                                <tr class="table-header">
                                                                    <th>Ítem</th>
                                                                    <th>Descripción</th>
                                                                    <th>Acciones</th>
                                                                </tr>
                                                                <tbody>
                                                                    {% for tipopago in list_tipo_pago %}
                                                                        {% if tipopago.tipo == 1 and tipopago.eliminado == 0  %}
                                                                            {% if tipopago.padre == None %}
                                                                                <tr>
                                                                                    <th scope="row">{{ forloop.counter }}</th>
                                                                                    <td>{{ tipopago.descripcion }}</td>
                                                                                    <td>
                                                                                        <div class="btn-group btn-group-sm" role="group" aria-label="...">

                                                                                            <a title="Detalle" href='{% url "payments:tipopago_detail" tipopago.id_tipo_pago %}' class="btn btn-default">
                                                                                                <i class="fa fa-info-circle" aria-hidden="true"></i>
                                                                                            </a>
                                                                                            <a title="Eliminar" href="{% url 'payments:tipopago_delete' tipopago.id_tipo_pago %}" class="btn btn-default">
                                                                                                <i class="fa fa-trash" aria-hidden="true"></i>
                                                                                            </a>
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>
                                                                            {% endif %}
                                                                        {% endif %}
                                                                    {% endfor %}
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>



                          </div>


                        <!-- FIN DE Servicios -->

                        <!-- FIN DE LA LISTA DE REGISTRO -->
                      </div>
                    </div>
                  </div>
                  <div class="col-md-3">

                  </div>
                </div>
              </div>
          </div>
      </div>
    </section>
    <!-- /.FIN DE CONTENIDO -->
  </div>
  <!-- /.FIN DE CONTENEDOR DE FORMULARIO  -->

{% endblock container %}