src/APIs/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from .views import UserInfoListView, SnippetDetail, ApoderadoInfo, DocenteInfo

urlpatterns = [

    url(r'^colegio_api/$', views.ColegioList.as_view()),
    url(r'^colegio_api/(?P<pk>\d+)/$', views.ColegioDetail.as_view()),
    url(r'^perfil_api/$', views.PerfilList.as_view()),
    url(r'^perfil_api/(?P<pk>\d+)/$', views.PerfilDetail.as_view()),
    ####################
    url(r'^apoderado_api/$', views.ApoderadoList.as_view()),
    url(r'^apoderado_api/(?P<pk>\d+)/$', views.ApoderadoDetail.as_view()),
    ###################
    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),
    ###################
    url(r'^apoderadoalumno_api/$', views.ApoderadoAlumnoList.as_view()),
    url(r'^apoderadoalumno_api/(?P<pk>\d+)/$', views.ApoderadoAlumnoDetail.as_view()),

    # http://127.0.0.1:8000/APIs/apoderadoalumno_api/?search=3

    ###################
    url(r'^matricula_api/$', views.MatriculaList.as_view()),
    url(r'^matricula_api/(?P<pk>\d+)/$', views.MatriculaDetail.as_view()),
    ###################

    # URL para el Web Service del Módulo Académico
    url(r'^asistencia_api/$', views.AsistenciaList.as_view()),
    url(r'^asistencia_api/(?P<pk>\d+)/$', views.AsistenciaDetail.as_view()),

    url(r'^aula_api/$', views.AulaList.as_view()),
    url(r'^aula_api/(?P<pk>\d+)/$', views.AulaDetail.as_view()),

    # url(r'^curso_docente_api/$', views.CursoDocenteList.as_view()),

    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),

    # URL para el Web Service del Módulo Académico
    url(r'^asistencia_api/$', views.AsistenciaList.as_view()),
    url(r'^asistencia_api/(?P<pk>\d+)/$', views.AsistenciaDetail.as_view()),

    url(r'^aula_api/$', views.AulaList.as_view()),
    url(r'^aula_api/(?P<pk>\d+)/$', views.AulaDetail.as_view()),

    # url(r'^curso_docente_api/$', views.CursoDocenteList.as_view()),


    url(r'^matricula_api/$', views.MatriculaList.as_view()),
    url(r'^matricula_api/(?P<pk>\d+)/$', views.MatriculaDetail.as_view()),

    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),

    url(r'^user_info/$', UserInfoListView.as_view(), name='user_info'),
    # url(r'^profesor_info/$', UserInfoListView.as_view(), name='profesor_info'),
    url(r'^apoderado_info/$', ApoderadoInfo, name='apoderado_info'),
    url(r'^docente_info/$', DocenteInfo, name='docente_info'),

    url(r'^colegio/(?P<pk>[0-9]+)/(?P<nombre>\w+)/$', SnippetDetail.as_view()),

    url(r'^curso_docente_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.CursoDocenteList.as_view()),

    # Web Service para obtener las ALUMNOS asociados a un aula determinado
    url(r'^aula_alumnos_api/(?P<pk>[0-9]+)/(?P<aula>\w+)/$', views.AulaAlumnosList.as_view()),

    # Web Service para obtener las CURSOS a las que enseña un docente determinado
    url(r'^docente_curso_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.DocenteCursoList.as_view()),

    # Web Service para obtener las AULAS a las que enseña un docente determinado
    url(r'^docente_aula_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.DocenteAulaList.as_view()),

    # Web Service para visualizar las ASISTENCIAS POR MES de un aula determinada
    url(r'^aula_asistencia_api/(?P<pk>[0-9]+)/(?P<aula>\w+)/(?P<mes>\w+)/$', views.AulaAsistenciaList.as_view()),

    # webservice prueba
    url(r'^relacionusuarioperfil/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.RelacionUsuarioPerfilView.as_view()),
    url(r'^relacionperfilalumno/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.RelacionPerfilAlumnoView.as_view()),

    #################################################################################################################
    url(r'^personaemisor_api/$', views.PersonaEmisorList.as_view()),
    url(r'^personaemisor_api/(?P<pk>\d+)/$', views.PersonaEmisorDetail.as_view()),
    ###################
    url(r'^personareceptor_api/$', views.PersonaReceptorList.as_view()),
    url(r'^personareceptor_api/(?P<pk>\d+)/$', views.PersonaReceptorDetail.as_view()),
    ###################
    url(r'^tipoalerta_api/$', views.TipoAlertaList.as_view()),
    url(r'^tipoalerta_api/(?P<pk>\d+)/$', views.TipoAlertaDetail.as_view()),
    ####################
    url(r'^estadoalerta_api/$', views.EstadoAlertaList.as_view()),
    url(r'^estadoalerta_api/(?P<pk>\d+)/$', views.EstadoAlertaDetail.as_view()),
    ###################
    url(r'^contenidoalerta_api/$', views.ContenidoAlertaList.as_view()),
    url(r'^contenidoalerta_api/(?P<pk>\d+)/$', views.ContenidoAlertaDetail.as_view()),
    ###################
    url(r'^alerta_api/$', views.AlertaList.as_view()),
    url(r'^alerta_api/(?P<pk>\d+)/$', views.AlertaDetail.as_view()),

    ###################
    url(r'^token_f/$', views.TokenFirebaseList.as_view()),
    url(r'^token_f/(?P<pk>\d+)/$', views.TokenFirebaseDetail.as_view()),
    ###################
    url(r'^usuarios_permisos/$', views.GroupList.as_view()),
    url(r'^usuarios_permisos/(?P<pk>\d+)/$', views.GroupDetail.as_view()),

    ###################
    url(r'^colegio_personal/$', views.PersonalColegioList.as_view()),
    url(r'^colegio_personal/(?P<pk>\d+)/$', views.PersonalColegioDetail.as_view()),

    ###################
    url(r'^personal/$', views.PersonalList.as_view()),
    url(r'^personal/(?P<pk>\d+)/$', views.PersonalDetail.as_view()),
    ###################
    url(r'^alertadata_api/$', views.AlertaDataList.as_view()),
    url(r'^alertadata_api/(?P<pk>\d+)/$', views.AlertaDataDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/accounts/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

from .views import (
    # Registro de Usuarios
    RegistroUsarioListView,
    RegistroUsarioDetailView,
    RegistroUsarioUpdateView,

    # Sistemas, Director, Cajero, Tesorero
    RegistroUsarioCreationViewSistema,
    RegistroUsarioCreationViewDirector,
    RegistroUsarioCreationViewCajero,
    RegistroUsarioCreationViewTesorero,

    RegistroUsuario, RegistroUsuarioApoderado, RegistroUsarioCreationViewApoderado)

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [

    url(r'^error_usuario_sin_perfil/$', views.UsuarioSinPerfil),

    url(r'^api', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^rest-auth/', include('rest_auth.urls')),

    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^me$', views.AsignColegioView.as_view(), name='tocolegio_self'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$',
        views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),

    # Registro de Usuarios
    url(r'^register/$', RegistroUsarioListView.as_view(), name='register_accounts_list'),
    url(r'^register/(?P<pk>\d+)$', RegistroUsarioDetailView.as_view(), name='register_accounts_detail'),
    url(r'^register/update/(?P<pk>\d+)$', RegistroUsarioUpdateView.as_view(), name='register_accounts_edit'),

    # Sistemas, Director, Cajero, Tesorero
    url(r'^register/createSistema$', RegistroUsarioCreationViewSistema.as_view(),
        name='register_accounts_createSistema'),
    url(r'^register/createDirector$', RegistroUsarioCreationViewDirector.as_view(),
        name='register_accounts_createDirector'),
    url(r'^register/createCajero$', RegistroUsarioCreationViewCajero.as_view(), name='register_accounts_createCajero'),
    url(r'^register/createTesorero$', RegistroUsarioCreationViewTesorero.as_view(),
        name='register_accounts_createTesorero'),

    # $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    # Registers
    url(r'^register/create$', RegistroUsuario.as_view(), name='register_create'),
    url(r'^register/create2$', RegistroUsuarioApoderado.as_view(), name='register_apoderado_create'),
    # $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

    url(r'^register/createApoderado$', RegistroUsarioCreationViewApoderado.as_view(),
        name='register_accounts_createApoderado'),
]

src/colegio/urls.py
from django.conf.urls import include, url
from django.conf.urls import handler404
from colegio.views import mi_error_404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import enrollment.urls
import register.urls
import income.urls
import cash.urls
import payments.urls
import discounts.urls
import AE_academico.urls
import APIs.urls
import alerta.urls
from . import views

handler404 = mi_error_404

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^enrollments/', include(enrollment.urls, namespace='enrollments')),
    url(r'^registers/', include(register.urls, namespace='registers')),
    url(r'^cash/', include(cash.urls, namespace='cash')),
    url(r'^income/', include(income.urls, namespace='income')),
    url(r'^payments/', include(payments.urls, namespace='payments')),
    url(r'^discounts/', include(discounts.urls, namespace='discounts')),
    url(r'^academic/', include(AE_academico.urls, namespace='academic')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^APIs/', include(APIs.urls, namespace='apis')),
    url(r'^alerta/', include(alerta.urls, namespace='alerta')),

    url(r'^locale/', views.view_locale),
    url(r'^login_api/', views.Login_api_general.as_view()),
# url(r'^calendar/', include('schedule.urls', namespace='calendar')),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
                       url(r'^__debug__/', include(debug_toolbar.urls)),
                   ] + urlpatterns

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/profiles/forms.py
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import get_user_model

from . import models

User = get_user_model()


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('name', label='Usuario'),
            )

        if self.fields.get('name'):
            self.fields.get('name').label = 'Usuario'

    class Meta:
        model = User
        fields = ['name']


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('picture'),
            Field('bio'),
            Field('nombre'),
            Field('segundo_nombre'),
            Field('apellido_pa'),
            Field('apellido_ma'),
            Submit('update', 'Actualizar', css_class="btn-success"),
            )

    class Meta:
        model = models.Profile
        fields = ['picture', 'bio','nombre', 'segundo_nombre','apellido_pa','apellido_ma']
        labels = {
            'picture': 'Imagen de Perfil',
            'bio': 'Información sobre ti',
            'apellido_pa': 'Apellido Paterno',
            'apellido_ma': 'Apellido Materno',
        }

src/profiles/views.py
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from utils.middleware import get_current_colegio
from utils.views import MyLoginRequiredMixin
from . import forms
from . import models
from enrollment.models import Sucursal

class ShowProfile(MyLoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/show_profile.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        #kwargs["colegio1"] = Colegio.objects.get(pk = self.request.session.get('colegio'))
        return super(ShowProfile, self).get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
            #kwargs["profile_form"] = forms.ProfileForm(instance=user.persona)
        return super(EditProfile, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(request.POST,
                                         request.FILES,
                                         instance=user.profile)
                                         #instance=user.persona)
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(request, "There was a problem with the form. "
                           "Please check the details.")
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            #profile_form = forms.ProfileForm(instance=user.persona)
            return super(EditProfile, self).get(request,
                                                user_form=user_form,
                                                profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Profile details saved!")
        return redirect("profiles:show_self")

src/profiles/templates/profiles/edit_profile.html
{% extends "page.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

    <div class="container">
        <h1 class="text-primary">Editar Perfil</h1>
        <hr>
        <div class="row">
            <!-- left column -->
            <div class="col-md-3">
                <div class="text-center">
                    <img title="profile picture" class="img-circle img-responsive"
                         src="{% thumbnail user.profile.picture|default:'default_profile.png' 140x140 crop %}">
                </div>
            </div>

            <!-- edit form column -->
            <div class="col-md-8">
                <h3>Información Personal</h3>
                <form enctype="multipart/form-data" method="post">
                    {% crispy user_form %}
                    {% crispy profile_form %}
                    <a class="btn btn-default pull-right" href="{% url 'accounts:password-change' %}">Cambiar Contraseña</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/profiles/templates/profiles/show_profile.html
{% extends "page.html" %}

{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

{% block container %}

    <div class="container profile-head">
        <div class="row">
            <div class="col-sm-9">
                <h1>{{ show_user.get_full_name }}</h1>
                {% if editable %}
                    <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Editar Perfil</a>
                {% endif %}
            </div>
            <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive"
                                       src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 140x140 crop %}">
            </div>
        </div>
    </div>

    <div class="container profile-body">
        <div class="row">
            <div class="col-sm-4">
                <ul class="list-group">
                    <li class="list-group-item text-muted">Perfil</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong>Email:</strong></span>
                        {{ show_user.email|default:"missing" }}
                        {% if show_user.profile.email_verified %}
                            <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"
                                  title="Este correo electrónico ha sido verificado"></span>
                            <span class="sr-only">Verified</span>
                        {% else %}
                            <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"
                                  title="Este correo electrónico no esta verificado"></span>
                            <span class="sr-only">Not Verified</span>
                        {% endif %}
                    </li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Fecha Ingreso:</strong></span> {{ show_user.date_joined }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Última Conexión:</strong></span> {{ show_user.last_login }}</li>
                </ul>
            </div>
            <div class="col-sm-7">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ show_user.get_full_name }}
                        {% if show_user.profile.slug %}
                            <a href="{% url 'profiles:show' show_user.profile.slug %}">
                                <span class="glyphicon glyphicon-link" aria-hidden="true"
                                      title="Profile permalink"></span>
                                <span class="sr-only">Permalink</span></a>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <strong>Nombre </strong>:
                        {{ show_user.profile.nombre }}
                        <br>
                    <strong>Apellido paterno </strong>:
                        {{ show_user.profile.apellido_pa }}
                        <br>

                        <strong>Sobre mí </strong>:
                        {% if show_user.profile.bio == None %}
                            No hay información guardada
                        {% else %}
                            {{ show_user.profile.bio }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}