src/APIs/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from .views import UserInfoListView, SnippetDetail, ApoderadoInfo, DocenteInfo

urlpatterns = [

    url(r'^colegio_api/$', views.ColegioList.as_view()),
    url(r'^colegio_api/(?P<pk>\d+)/$', views.ColegioDetail.as_view()),
    url(r'^perfil_api/$', views.PerfilList.as_view()),
    url(r'^perfil_api/(?P<pk>\d+)/$', views.PerfilDetail.as_view()),
    ####################
    url(r'^apoderado_api/$', views.ApoderadoList.as_view()),
    url(r'^apoderado_api/(?P<pk>\d+)/$', views.ApoderadoDetail.as_view()),
    ###################
    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),
    ###################
    url(r'^apoderadoalumno_api/$', views.ApoderadoAlumnoList.as_view()),
    url(r'^apoderadoalumno_api/(?P<pk>\d+)/$', views.ApoderadoAlumnoDetail.as_view()),

    # http://127.0.0.1:8000/APIs/apoderadoalumno_api/?search=3

    ###################
    url(r'^matricula_api/$', views.MatriculaList.as_view()),
    url(r'^matricula_api/(?P<pk>\d+)/$', views.MatriculaDetail.as_view()),
    ###################

    # URL para el Web Service del Módulo Académico
    url(r'^asistencia_api/$', views.AsistenciaList.as_view()),
    url(r'^asistencia_api/(?P<pk>\d+)/$', views.AsistenciaDetail.as_view()),

    url(r'^aula_api/$', views.AulaList.as_view()),
    url(r'^aula_api/(?P<pk>\d+)/$', views.AulaDetail.as_view()),

    # url(r'^curso_docente_api/$', views.CursoDocenteList.as_view()),

    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),

    # URL para el Web Service del Módulo Académico
    url(r'^asistencia_api/$', views.AsistenciaList.as_view()),
    url(r'^asistencia_api/(?P<pk>\d+)/$', views.AsistenciaDetail.as_view()),

    url(r'^aula_api/$', views.AulaList.as_view()),
    url(r'^aula_api/(?P<pk>\d+)/$', views.AulaDetail.as_view()),

    # url(r'^curso_docente_api/$', views.CursoDocenteList.as_view()),


    url(r'^matricula_api/$', views.MatriculaList.as_view()),
    url(r'^matricula_api/(?P<pk>\d+)/$', views.MatriculaDetail.as_view()),

    url(r'^alumno_api/$', views.AlumnoList.as_view()),
    url(r'^alumno_api/(?P<pk>\d+)/$', views.AlumnoDetail.as_view()),

    url(r'^user_info/$', UserInfoListView.as_view(), name='user_info'),
    # url(r'^profesor_info/$', UserInfoListView.as_view(), name='profesor_info'),
    url(r'^apoderado_info/$', ApoderadoInfo, name='apoderado_info'),
    url(r'^docente_info/$', DocenteInfo, name='docente_info'),

    url(r'^colegio/(?P<pk>[0-9]+)/(?P<nombre>\w+)/$', SnippetDetail.as_view()),

    url(r'^curso_docente_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.CursoDocenteList.as_view()),

    # Web Service para obtener las ALUMNOS asociados a un aula determinado
    url(r'^aula_alumnos_api/(?P<pk>[0-9]+)/(?P<aula>\w+)/$', views.AulaAlumnosList.as_view()),

    # Web Service para obtener las CURSOS a las que enseña un docente determinado
    url(r'^docente_curso_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.DocenteCursoList.as_view()),

    # Web Service para obtener las AULAS a las que enseña un docente determinado
    url(r'^docente_aula_api/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.DocenteAulaList.as_view()),

    # Web Service para visualizar las ASISTENCIAS POR MES de un aula determinada
    url(r'^aula_asistencia_api/(?P<pk>[0-9]+)/(?P<aula>\w+)/(?P<mes>\w+)/$', views.AulaAsistenciaList.as_view()),

    # webservice prueba
    url(r'^relacionusuarioperfil/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.RelacionUsuarioPerfilView.as_view()),
    url(r'^relacionperfilalumno/(?P<pk>[0-9]+)/(?P<docente>\w+)/$', views.RelacionPerfilAlumnoView.as_view()),

    #################################################################################################################
    url(r'^personaemisor_api/$', views.PersonaEmisorList.as_view()),
    url(r'^personaemisor_api/(?P<pk>\d+)/$', views.PersonaEmisorDetail.as_view()),
    ###################
    url(r'^personareceptor_api/$', views.PersonaReceptorList.as_view()),
    url(r'^personareceptor_api/(?P<pk>\d+)/$', views.PersonaReceptorDetail.as_view()),
    ###################
    url(r'^tipoalerta_api/$', views.TipoAlertaList.as_view()),
    url(r'^tipoalerta_api/(?P<pk>\d+)/$', views.TipoAlertaDetail.as_view()),
    ####################
    url(r'^estadoalerta_api/$', views.EstadoAlertaList.as_view()),
    url(r'^estadoalerta_api/(?P<pk>\d+)/$', views.EstadoAlertaDetail.as_view()),
    ###################
    url(r'^contenidoalerta_api/$', views.ContenidoAlertaList.as_view()),
    url(r'^contenidoalerta_api/(?P<pk>\d+)/$', views.ContenidoAlertaDetail.as_view()),
    ###################
    url(r'^alerta_api/$', views.AlertaList.as_view()),
    url(r'^alerta_api/(?P<pk>\d+)/$', views.AlertaDetail.as_view()),

    ###################
    url(r'^token_f/$', views.TokenFirebaseList.as_view()),
    url(r'^token_f/(?P<pk>\d+)/$', views.TokenFirebaseDetail.as_view()),
    ###################
    url(r'^usuarios_permisos/$', views.GroupList.as_view()),
    url(r'^usuarios_permisos/(?P<pk>\d+)/$', views.GroupDetail.as_view()),

    ###################
    url(r'^colegio_personal/$', views.PersonalColegioList.as_view()),
    url(r'^colegio_personal/(?P<pk>\d+)/$', views.PersonalColegioDetail.as_view()),

    ###################
    url(r'^personal/$', views.PersonalList.as_view()),
    url(r'^personal/(?P<pk>\d+)/$', views.PersonalDetail.as_view()),
    ###################
    url(r'^alertadata_api/$', views.AlertaDataList.as_view()),
    url(r'^alertadata_api/(?P<pk>\d+)/$', views.AlertaDataDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/colegio/urls.py
from django.conf.urls import include, url
from django.conf.urls import handler404
from colegio.views import mi_error_404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import enrollment.urls
import register.urls
import income.urls
import cash.urls
import payments.urls
import discounts.urls
import AE_academico.urls
import APIs.urls
import alerta.urls
from . import views

handler404 = mi_error_404

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^enrollments/', include(enrollment.urls, namespace='enrollments')),
    url(r'^registers/', include(register.urls, namespace='registers')),
    url(r'^cash/', include(cash.urls, namespace='cash')),
    url(r'^income/', include(income.urls, namespace='income')),
    url(r'^payments/', include(payments.urls, namespace='payments')),
    url(r'^discounts/', include(discounts.urls, namespace='discounts')),
    url(r'^academic/', include(AE_academico.urls, namespace='academic')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^APIs/', include(APIs.urls, namespace='apis')),
    url(r'^alerta/', include(alerta.urls, namespace='alerta')),

    url(r'^locale/', views.view_locale),
    url(r'^login_api/', views.Login_api_general.as_view()),
# url(r'^calendar/', include('schedule.urls', namespace='calendar')),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
                       url(r'^__debug__/', include(debug_toolbar.urls)),
                   ] + urlpatterns

src/income/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

from income.views import ControlIngresosPadresView, ControlIngresosPromotorView, ControlIngresosPromotorDetallesView2, \
    boleta_A7
from income.views import ControlIngresosPromotorDetallesView, exportIngresosCSV
from income.views import RegistrarPagoListView
from income.views import recibo_A6, boleta_A6, recibo_A5, boleta_A5, FiltrarCuentas


urlpatterns = [
    url(r'^register/filter$', RegistrarPagoListView.as_view(), name="register"),
    url(r'^register/$', FiltrarCuentas.as_view(), name="filtrar_cuentas"),

    url(r'^exportar/$', exportIngresosCSV, name="export_ingresos"),

    url(r'^cuentas_cobrar_padres/filter', ControlIngresosPadresView.as_view(), name="cuentas_cobrar_padres"),

    url(r'^cuentas_cobrar_promotor/filter', ControlIngresosPromotorView.as_view(), name="cuentas_cobrar_promotor"),

    url(r'^cuentas_cobrar_promotor_detalle/filter', ControlIngresosPromotorDetallesView.as_view(), name="cuentas_cobrar_promotor_detalle"),

    url(r'^register/reciboA6/$', recibo_A6, name="recibo_A6"),
    url(r'^register/boletaA6/$', boleta_A6, name="boleta_A6"),
    url(r'^register/reciboA5/$', recibo_A5, name="recibo_A5"),
    url(r'^register/boletaA5/$', boleta_A5, name="boleta_A5"),
    url(r'^register/boletaA7/$', boleta_A7, name="boleta_A7"),

    url(r'^cuentas_cobrar_promotor_detalle2/filter', ControlIngresosPromotorDetallesView2.as_view(), name="cuentas_cobrar_promotor_detalle2"),

]

src/income/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from register.models import Apoderado, Profile
import logging
from utils.middleware import get_current_user

logger = logging.getLogger("project")

class CuentasCobrarPromotorForm(forms.Form):
    """
    Formulario para filtar los detalles de Control de ingresos
    Nota:
        solo se añaden com campos los que son definidos por los usuarios
    """

    anio = forms.CharField()
    mes = forms.CharField()

    def ChoiceAnio(self):
        MY_CHOICES = (
            ('2017', '2017'),
            ('2016', '2016'),
        )
        return MY_CHOICES

    def ChoiceMes(self):
        MY_CHOICES = (
            ('Todos', 'Todos'),
            ('Enero', 'Enero'),
            ('Febrero', 'Febrero'),
            ('Marzo', 'Marzo'),
            ('Abril', 'Abril'),
            ('Mayo', 'Mayo'),
            ('Junio', 'Junio'),
            ('Julio', 'Julio'),
            ('Agosto', 'Agosto'),
            ('Setiembre', 'Setiembre'),
            ('Octubre', 'Octubre'),
            ('Noviembre', 'Noviembre'),
            ('Diciembre', 'Diciembre'),
        )
        return MY_CHOICES

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['anio'] = forms.ChoiceField(choices=self.ChoiceAnio())
        self.fields['mes'] = forms.ChoiceField(choices=self.ChoiceMes())
        self.fields['anio'].widget.attrs.update({'class': 'form-control'})
        self.fields['mes'].widget.attrs.update({'class': 'form-control'})


class CuentasCobrarPromotorDetalleForm(forms.Form):
    """
    Formulario para filtar los detalles de Control de ingresos
    Nota:
        solo se añaden com campos los que son definidos por los usuarios
    """

    alumno = forms.CharField()
    anio = forms.CharField()
    mes = forms.CharField()
    estado = forms.CharField()

    def ChoiceAnio(self):
        MY_CHOICES = (
            ('Todos', 'Todos'),
            ('2017', '2017'),
            ('2016', '2016'),
        )
        return MY_CHOICES

    def ChoiceMes(self):
        MY_CHOICES = (
            ('Todos', 'Todos'),
            ('Enero', 'Enero'),
            ('Febrero', 'Febrero'),
            ('Marzo', 'Marzo'),
            ('Abril', 'Abril'),
            ('Mayo', 'Mayo'),
            ('Junio', 'Junio'),
            ('Julio', 'Julio'),
            ('Agosto', 'Agosto'),
            ('Setiembre', 'Setiembre'),
            ('Octubre', 'Octubre'),
            ('Noviembre', 'Noviembre'),
            ('Diciembre', 'Diciembre'),
        )
        return MY_CHOICES

    def ChoiceEstado(self):
        MY_CHOICES = (
            ('Todos', 'Todos'),
            ('Pagado', 'Pagado'),
            ('No_pagado', 'No pagado'),
        )
        return MY_CHOICES

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['anio'] = forms.ChoiceField(choices=self.ChoiceAnio())
        self.fields['mes'] = forms.ChoiceField(choices=self.ChoiceMes())
        self.fields['estado'] = forms.ChoiceField(choices=self.ChoiceEstado())
        self.fields['alumno'].widget.attrs.update({'class': 'form-control'})
        self.fields['anio'].widget.attrs.update({'class': 'form-control'})
        self.fields['mes'].widget.attrs.update({'class': 'form-control'})
        self.fields['estado'].widget.attrs.update({'class': 'form-control'})

class CuentasCobrarPadresForm(forms.Form):

    alumno = forms.CharField()
    mes = forms.CharField()
    estado = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

src/income/templates/control_ingresos_promotor_detalle.html
{% extends "page.html" %}

{% block title %}{{ block.super }}Ingresos{% endblock %}

{% block titulo %}
      <h1>
        Detalle de Ingresos
        <small>Módulo de Facturación</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li>Módulo de Facturación</li>
        <li class="active">Detalle de Ingresos</li>
      </ol>
{% endblock %}

<body>
{% block container %}
{% load crispy_forms_tags %}

{% if mensaje_error %}
    {{ mensaje_error }}
{% else %}
<!-- INICIO DE CONTENIDO -->
    <section>
      <div class="row">
          <div class="col-md-12">
              <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Detalle de Control de Ingresos</h3>
                </div>
                <div class="box-body">
                  <div class="col-md-12">
                    <div class="panel-page">
                      <div class="toolbar-search">
                        <div class="box-body">
                           <form action="" method="POST" class="form-horizontal" id="1">{% csrf_token %}
                                {% csrf_token %}
                                    <div class="col-md-3">
                                      <div class="form-group">
                                      <label>Alumno</label>
                                        <input type="text" name="alumno" class="form-control" placeholder="Escriba nombre o apellido">
                                      </div>
                                    </div>
                                    <div class="col-md-2">
                                      <div class="form-group">
                                      <label>Año</label>
                                        <select name="anio"  class="form-control">
                                            {% for anio in anios %}
                                                {% if anio_actual == anio %}
                                                    <option selected>{{ anio }}</option>
                                                {%  else %}
                                                    <option>{{ anio }}</option>
                                                {% endif %}
                                            {% endfor %}
                                        </select>
                                      </div>
                                    </div>
                                    <div class="col-md-2">
                                      <div class="form-group">
                                      <label>Mes</label>
                                        <select name="mes"  class="form-control">
                                            {% for mes in meses %}
                                                <option>{{ mes }}</option>
                                            {% endfor %}
                                        </select>
                                      </div>
                                    </div>
                                    <div class="col-md-2">
                                      <div class="form-group">
                                      <label>Estado</label>
                                        <select name="estado"  class="form-control">
                                            {% for estado in estados %}
                                                <option>{{ estado }}</option>
                                            {% endfor %}
                                        </select>
                                      </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="search-actions">
                                          <button type="submit" class="btn btn-primary btn-block">
                                          <i class="fa fa-search" aria-hidden="true"></i>
                                           Consultar
                                          </button>
                                        </div>
                                    </div>
                            </form>
                        </div>
                    </div>
                    {% if object_list %}
                        <table class="table table-hover">
                            <tbody>
                            <tr>
                                <th>Alumno</th>
                                <th>Concepto</th>
                                <th>Fecha de vencimiento</th>
                                <th>Monto cancelado</th>
                                <th>Importe a pagar S/.</th>
                                <th>Estado</th>
                            </tr>
                            <div id="div1">
                                <tr>
                                    {% for cuenta in object_list %}
                                        {% if not cuenta.orderDate %}
                                            <tr>
                                                <td>{{ cuenta.matricula.alumno.getNombreCompleto }}</td>
                                                {% if not cuenta.servicio.tipo_servicio.extra %}
                                                    <td>{{ cuenta.servicio.nombre }}</td>
                                                {% else %}
                                                    <td>{{ cuenta.servicio.tipo_servicio }}</td>
                                                {% endif %}
                                                <td>{{ cuenta.fecha_ven }}</td>
                                                <td>S/.{{ cuenta.getMonto }}</td>
                                                <td>S/.{{ cuenta.deuda }}</td>
                                                {% if cuenta.estado %}
                                                    <td>
                                                        <span class="label label-danger">No pagado</div>
                                                    </td>
                                                {% else %}
                                                    <td>
                                                        <span class="label label-success">Pagado</div>
                                                    </td>
                                                {% endif %}
                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                                </tbody>
                            </div>
                        </table>
                        <div class="col-md-2">
                                <div class="search-actions">
                                    <form action="{% url 'income:export_ingresos' %}">
                                        <button type="submit" value="Detalle" class="btn btn-default">
                                            <i class="fa fa-circle" aria-hidden="true"></i>
                                            Exportar
                                        </button>
                                    </form>
                                </div>
                            </div>
                    {% endif %}
                    </div>
                  </div>


                </div>
                <div class="col-md-3"></div>

                </div>

              </div>
          </div>
      </div>
    </section>
<!-- /.FIN DE CONTENIDO -->
{% endif %}
{% endblock container %}

</body>

src/income/templates/detalles_pago.html
{%  extends "page.html" %}

{% block title %}{{ block.super }}Ingresos{% endblock %}

{% block titulo %}
      <h1>
        Detalle de Registro de Ingreso
        <small>Módulo de Facturación</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li>Módulo de Facturación</li>
        <li class="active">Detalle de Registro de Ingreso</li>
      </ol>
{% endblock %}

{% block container %}
<section>
      <div class="row">
          <div class="col-md-12">
              <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Detalle de Registro de Ingreso</h3>
                </div>
                <div class="box-body">

                  <div id="detalle" class="detalle">

                    <div class="col-md-8">
                      <div class="alert alert-info" role="alert">
                        <p>
                        <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                        El registro se realizó con exito, a continuación puede imprimir o enviar por correo el detalle del pago
                        </p>
                      </div>
                      <div class="border-detalle">
                        <div class="row">
                          <div class="col-md-6">
                              <div class="logotipo">
                                Logotipo
                              </div>
                              <h3>{{ colegio.nombre }}</h3>
                              <p>RUC {{ colegio.ruc }}</p>
                          </div>
                          <div class="col-md-6">
                            <dl class="dl-horizontal">
                              <dt>
                                  N° de Recibo:
                              </dt>
                              <dd>
                                  {{ colegio.numero_recibo }}
                              </dd>
                              <dt>
                                  Nombres del cliente:
                              </dt>
                              <dd>
                                  {{ alumno }}
                              </dd>
                              <dt>
                                  Grado y Sección:
                              </dt>
                              <dd>
                                  {{ tiposervicio }}
                              </dd>
                              <dt>
                                  Fecha de pago:
                              </dt>
                              <dd>
                                  {{ fecha }}
                              </dd>
                              <dt>
                                  Cajero de registro:
                              </dt>
                              <dd>
                                  {{ cajero }}
                              </dd>
                            </dl>
                          </div>

                        </div>

                      </div>
                      <div class="border-detalle">
                          <table class="table table-bordered">
                            <tr class="table-header">
                              <th>ID</th>
                              <th>Descripción Producto</th>
                              <th>Precio/Costo</th>

                            </tr>
                              {% for servicio in servicios %}
                            <tr>
                              <td>183</td>
                              <td>{{ servicio.cuentascobrar.servicio.nombre }} de {{ servicio.cuentascobrar.servicio.tipo_servicio }} del {{ servicio.cuentascobrar.fecha_ven }}</td>
                              <td>{{ servicio.monto }}</td>

                            </tr>
                              {% empty %}
                              {% endfor %}

                            </tr>
                            <tr>
                              <td colspan="2" class="table-bold-print">Sub Total</td>
                              <td class="table-price-print">S/.{{ subtotal }}</td>
                            </tr>
                            <tr>
                              <td colspan="2" class="table-bold-print">Descuento</td>
                              <td class="table-price-print">S/.{{ descuento }}</td>
                            </tr>
                            <tr>
                              <td colspan="2" class="table-bold-print">Total</td>
                              <td class="table-price-print">S/.{{ total }}</td>
                            </tr>

                          </table>
                      </div>
                      <div class="border-detalle">


                          <form name="imprimirreciboA6" id="imprimirreciboA6">{% csrf_token %}
                              <div class="col-md-5">
                                  <input hidden id="cobranza" name="cobranza" value="{{ cobranza }}" >
                                  <input hidden id="alumno" name="alumno" value="{{ alumno.id_alumno }}" >
                                  <button formmethod="post" formaction="{% url 'income:recibo_A6' %}" form="imprimirreciboA6" class="btn btn-success" ><i class="fa fa-print" aria-hidden="true"></i> Imprimir recibo A6</button>
                          </div>
                          </form>
                          <form name="imprimirreciboA5" id="imprimirreciboA5">{% csrf_token %}
                              <div class="col-md-5">
                                  <input hidden id="cobranza" name="cobranza" value="{{ cobranza }}" >
                                  <input hidden id="alumno" name="alumno" value="{{ alumno.id_alumno }}" >
                                  <button formmethod="post" formaction="{% url 'income:recibo_A5' %}" form="imprimirreciboA5" class="btn btn-success" ><i class="fa fa-print" aria-hidden="true"></i> Imprimir recibo A5</button>
                          </div>
                          </form>
                          <form name="imprimirboletaA6" id="imprimirboletaA6">{% csrf_token %}
                              <div class="col-md-5">
                                  <input hidden id="cobranza" name="cobranza" value="{{ cobranza }}" >
                                  <input hidden id="alumno" name="alumno" value="{{ alumno.id_alumno }}" >
                                  <button formmethod="post" formaction="{% url 'income:boleta_A6' %}" form="imprimirboletaA6" class="btn btn-success" ><i class="fa fa-print" aria-hidden="true"></i> Imprimir boleta A6</button>
                          </div>
                          </form>
                          <form name="imprimirboletaA5" id="imprimirboletaA5">{% csrf_token %}
                              <div class="col-md-5">
                                  <input hidden id="cobranza" name="cobranza" value="{{ cobranza }}" >
                                  <input hidden id="alumno" name="alumno" value="{{ alumno.id_alumno }}" >
                                  <button formmethod="post" formaction="{% url 'income:boleta_A5' %}" form="imprimirboletaA5" class="btn btn-success" ><i class="fa fa-print" aria-hidden="true"></i> Imprimir boleta A5</button>
                          </div>
                          </form>
                          <form name="imprimirboletaA7" id="imprimirboletaA7">{% csrf_token %}
                              <div class="col-md-5">
                                  <input hidden id="cobranza" name="cobranza" value="{{ cobranza }}" >
                                  <input hidden id="alumno" name="alumno" value="{{ alumno.id_alumno }}" >
                                  <button formmethod="post" formaction="{% url 'income:boleta_A7' %}" form="imprimirboletaA7" class="btn btn-success" ><i class="fa fa-print" aria-hidden="true"></i> Imprimir Ticket</button>
                          </div>
                          </form>
                      </div>
                    </div>
                    <div class="col-md-4">

                    </div>

                  </div>
                </div>
              </div>
          </div>
      </div>
</section>
{% endblock %}